import { expect,test } from '@playwright/test';
import { newGame } from '../../lib/game/engine';

test('rules are always available',async({page})=>{await page.goto('/');await page.getByTestId('rules-button').click();await expect(page.getByRole('dialog',{name:'完整规则'})).toContainText('进贡与还贡');await page.getByTestId('close-rules').click();await expect(page.getByRole('dialog')).toHaveCount(0)});
test('beginner path reaches a readable, paced AI table',async({page})=>{await page.addInitScript(()=>{Date.now=()=>20260820});await page.goto('/');await page.getByTestId('start-game').click();for(let i=0;i<3;i++)await page.getByRole('button',{name:'下一节 →'}).click();await page.getByTestId('lesson-start-game').click();await expect(page.getByText('你与小顾一队')).toBeVisible();await expect(page.getByText(/陈总/).first()).toBeVisible();await expect(page.getByTestId('save-mode')).toContainText(/存档 · (本机|完成后保存)/);await expect(page.getByTestId('voice-toggle')).toContainText('语音 OFF');await expect(page.getByTestId('ai-speed')).toContainText('舒缓档 · 起步 1.4s');await page.getByTestId('ai-speed').click();await expect(page.getByTestId('ai-speed')).toContainText('讲解档 · 起步 2.2s');expect(await page.getByTestId('rank-group').count()).toBeGreaterThan(1);await page.getByTestId('hint-button').click();await expect(page.locator('.hand .playing-card[aria-pressed="true"]')).not.toHaveCount(0);await page.getByTestId('play-button').click();await expect(page.getByText(/这手是/)).toBeVisible();await expect(page.getByTestId('live-history')).toContainText('你')});
test('nine-grid memory drill randomizes and can be completed',async({page})=>{await page.goto('/');await page.getByRole('button',{name:'记牌九宫格'}).click();const labels=await page.locator('.memory-tile').allTextContents();await page.getByTestId('memory-hide').click();const prompt=await page.getByTestId('memory-prompt').textContent(),targets=prompt!.replace('请找出：','').split('、');for(const label of targets){const index=labels.indexOf(label);expect(index).toBeGreaterThanOrEqual(0);await page.getByTestId(`memory-${index}`).click()}await page.getByTestId('memory-submit').click();await expect(page.getByText('本轮得分 3 / 3')).toBeVisible();await page.getByRole('button',{name:'进入下一轮'}).click();await expect(page.getByText('第 2 轮')).toBeVisible()});
test('four guests match into a private server-authoritative room',async({browser},testInfo)=>{test.skip(testInfo.project.name!=='desktop','one cross-context room test is sufficient');const contexts=await Promise.all(Array.from({length:4},()=>browser.newContext()));try{const pages=await Promise.all(contexts.map(async context=>{const page=await context.newPage();await page.goto('/');await expect(page.getByTestId('online-match')).toBeVisible();await page.getByTestId('online-match').click();await page.getByTestId('join-online').click();return page}));for(const page of pages)await expect(page.getByText('真人牌桌 · 打')).toBeVisible({timeout:10000});let actor=null;for(const page of pages){if(await page.getByText(/轮到你 · \d+s/u).isVisible()){actor=page;break}}expect(actor).toBeTruthy();const active=actor!;await active.locator('.online-hand .playing-card').last().click();await active.getByTestId('online-play').click();await expect(active.getByText(/服务器公平发牌 · 版本 1/u)).toBeVisible();active.once('dialog',dialog=>dialog.accept());await active.getByRole('button',{name:'离开并取消本局'}).click();await expect(pages.find(page=>page!==active)!.getByText('牌局已取消')).toBeVisible({timeout:5000})}finally{await Promise.all(contexts.map(context=>context.close()))}});
test('online lobby is usable on mobile',async({page},testInfo)=>{test.skip(testInfo.project.name!=='mobile','mobile-only coverage');await page.goto('/');await page.getByTestId('online-match').click();await expect(page.getByRole('heading',{name:'四人真人匹配'})).toBeVisible();await page.getByTestId('join-online').click();await expect(page.getByText(/等待牌友 · 已到/u)).toBeVisible();await page.getByRole('button',{name:'离开队列'}).click();await expect(page.getByTestId('join-online')).toBeVisible()});
test('a locally queued finished game resumes cloud sync after reload',async({page},testInfo)=>{test.skip(testInfo.project.name!=='desktop','one persistence lifecycle test is sufficient');const replay={...newGame(987654),phase:'finished' as const};await page.addInitScript(game=>localStorage.setItem('gd-history-v2',JSON.stringify([game])),replay);let posts=0;await page.route('**/api/progress',async route=>{if(route.request().method()==='POST'){posts++;await new Promise(resolve=>setTimeout(resolve,300));await route.fulfill({status:200,contentType:'application/json',body:'{"stored":true}'})}else await route.continue()});await page.goto('/');await page.getByRole('button',{name:'记牌九宫格'}).click();await expect.poll(()=>posts).toBe(1);await expect.poll(async()=>await page.evaluate(()=>JSON.parse(localStorage.getItem('gd-cloud-synced-v1')||'[]') as number[])).toContain(987654)});
