'use client';

import { useEffect, useRef, useState } from 'react';
import { analyzeStyle } from '@/lib/game/analysis';
import { localTrainingAgent, observe, safeAgentMove } from '@/lib/game/ai';
import { cardLabel, createDeck, RANK_LABEL } from '@/lib/game/cards';
import { legalPlay, newGame, nextRound, passTurn, playCards, resultLabel } from '@/lib/game/engine';
import { comboName, parseCombo } from '@/lib/game/rules';
import type { Card, GameState } from '@/lib/game/types';

type View='home'|'lesson'|'game'|'memory'|'replay';
const RULES=[
  ['01 · 目标与搭档','四人使用两副牌，共 108 张。对家是固定搭档。每副按出完顺序定头游、二游、三游、末游；搭档双上升 3 级，头游三游升 2 级，头游末游升 1 级。'],
  ['02 · 牌点大小','普通单牌由 2 到 A；当前级牌高于 A，低于小王、大王。红桃级牌是“逢人配”，在多张组合里可代替 2—A，但不能变成王。'],
  ['03 · 基本牌型','单张、对子、三张、三带二、五张顺子、三连对（木板）、二连三（钢板）。普通牌型只能用相同类型、相同张数且点数更大的牌压制。'],
  ['04 · 炸弹','四至八张及以上同点牌为炸弹；炸弹张数越多越大，同张数比较点数。五张同花顺高于五张炸弹、低于六张及以上炸弹；四王炸最大。炸弹可压普通牌。'],
  ['05 · 出牌与过牌','领出者可出任意合法牌型。其余玩家依次压牌或过牌；若后续有人改变了最大牌，之前过牌者再次轮到时仍可压牌。其余玩家连续过牌后，最后出牌者获得下一圈领出权。'],
  ['06 · 接风','某玩家最后一手无人压制且已经出完时，由其搭档“接风”领出；若搭档也已出完，则按座次交给下一位仍有手牌的玩家。'],
  ['07 · 进贡与还贡','上一副末游向头游进贡除红桃级牌外的最大牌；双下时两名下家分别进贡，头游取得较大贡牌，该贡牌的进贡者先出。收贡者须还实际牌点不高于 10 的牌（级牌不能作为低点还出）。单贡者持两张大王，或双贡双方合计持两张大王时抗贡。'],
  ['08 · 双上与报牌','同队取得头游、二游即“双上”，本副立即自然结束，另两家双下。手牌剩 10 张或更少时应按牌桌约定报牌，训练桌会始终显示每位玩家的剩余张数。'],
  ['09 · 升级与过 A','双方从 2 起级，双上升 3 级、头游三游升 2 级、头游末游升 1 级。正在打 A 的一方必须取得头游且搭档不能是末游才算过 A；头游末游则继续打 A。'],
  ['10 · 首出与牌桌变体','首副由随机座位先出；后续按进贡结果或抗贡规则确定。不同地区对顺子、同花顺展示、报牌时点可能不同，开桌前应确认采用 2022 竞技规则还是本地变体。'],
];
const LESSONS=[{n:'01',t:'一眼认牌型',d:'单张、对子到炸弹，先学会“这是什么”',m:'4 分钟'},{n:'02',t:'轮到我该做什么',d:'领出、压牌、过牌和接风',m:'4 分钟'},{n:'03',t:'老板局不冷场',d:'少停顿、会回应、不给暗号',m:'3 分钟'},{n:'04',t:'九宫格记关键牌',d:'只记王、级牌、A、2 和炸弹材料',m:'4 分钟'}];

export default function GuandanApp(){
  const [view,setView]=useState<View>('home');const [rules,setRules]=useState(false);const [lesson,setLesson]=useState(0);const [game,setGame]=useState<GameState>(()=>newGame(20260822));
  const [selected,setSelected]=useState<string[]>([]);const [coach,setCoach]=useState('提示已开启：系统会解释每一次出牌。');const [history,setHistory]=useState<GameState[]>([]);
  useEffect(()=>{document.documentElement.dataset.hydrated='true';return()=>{delete document.documentElement.dataset.hydrated}},[]);
  useEffect(()=>{const id=setTimeout(()=>{try{const raw=localStorage.getItem('gd-history-v2');if(!raw)return;const data=JSON.parse(raw);if(!Array.isArray(data))throw new Error('invalid history');setHistory(data.filter(g=>g&&g.schemaVersion===2&&Array.isArray(g.events)&&Array.isArray(g.players)))}catch{localStorage.removeItem('gd-history-v2')}},0);return()=>clearTimeout(id)},[]);
  useEffect(()=>{if(view!=='game'||game.phase!=='playing'||game.turn===0)return;let cancelled=false;const id=setTimeout(async()=>{try{const move=await safeAgentMove(localTrainingAgent,observe(game,game.turn));if(!cancelled)setGame(move?playCards(game,game.turn,move):passTurn(game,game.turn))}catch{if(cancelled)return;try{setGame(game.lastPlay?passTurn(game,game.turn):playCards(game,game.turn,[game.players[game.turn].hand[0].id]))}catch{setCoach('AI 动作校验失败，已安全暂停。请开始新比赛。')}}},320);return()=>{cancelled=true;clearTimeout(id)}},[game,view]);
  useEffect(()=>{if(game.phase!=='finished'||history.some(h=>h.seed===game.seed))return;const id=setTimeout(()=>{setHistory(current=>{if(current.some(h=>h.seed===game.seed))return current;const next=[game,...current].slice(0,12);localStorage.setItem('gd-history-v2',JSON.stringify(next));return next})},0);return()=>clearTimeout(id)},[game,history]);
  const start=()=>{setGame(newGame(Math.floor(Date.now()%2147483647)));setSelected([]);setCoach('你的回合：先试着出最小的单张，建立节奏。');setView('game')};
  const continueMatch=()=>{setGame(nextRound(game,Math.floor(Date.now()%2147483647)));setSelected([]);setCoach('新一副已完成贡还牌。注意谁获得了首出权。')};
  const onPlay=()=>{const valid=legalPlay(game,0,selected);if(!valid.ok){setCoach(`不能这样出：${valid.reason}`);return}const cards=game.players[0].hand.filter(c=>selected.includes(c.id)),combo=parseCombo(cards,game.level)!;setGame(playCards(game,0,selected));setSelected([]);setCoach(`这手是${comboName(combo)}。${combo.kind.includes('bomb')?'炸弹已记录：确认它值得换取这一圈控制权。':'出牌有效，继续观察搭档剩余张数。'}`)};
  return <main className="min-h-screen bg-[var(--ink)] text-[var(--paper)]"><div className="pixel-grid min-h-screen"><TopNav view={view} setView={setView} setRules={setRules}/>{view==='home'&&<Home start={start} setView={setView}/>} {view==='lesson'&&<Lesson lesson={lesson} setLesson={setLesson} start={start}/>} {view==='game'&&<Game state={game} selected={selected} setSelected={setSelected} onPlay={onPlay} onPass={()=>{try{setGame(passTurn(game,0));setCoach('已过牌。观察这一圈由谁取得出牌权。')}catch(e){setCoach((e as Error).message)}}} coach={coach} restart={start} nextDeal={continueMatch} setView={setView}/>} {view==='memory'&&<Memory/>} {view==='replay'&&<Replay history={history}/>} {rules&&<Rulebook close={()=>setRules(false)}/>}</div></main>;
}

function TopNav({view,setView,setRules}:{view:View;setView:(v:View)=>void;setRules:(v:boolean)=>void}){const links=([['home','训练大厅'],['lesson','极速课程'],['memory','记牌九宫格'],['replay','对局档案']] as [View,string][]);return <><header className="sticky top-0 z-30 border-b-2 border-slate-700 bg-[var(--ink)]/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-8"><button onClick={()=>setView('home')} className="flex items-center gap-3 text-left"><span className="logo-mark small">G</span><span><b className="block text-sm tracking-[.14em]">掼蛋特训局</b><small className="text-[9px] tracking-[.22em] text-[var(--mint)]">GUANDAN BOOTCAMP</small></span></button><nav className="hidden items-center gap-1 md:flex">{links.map(([v,l])=><button key={v} onClick={()=>setView(v)} className={`nav-link ${view===v?'active':''}`}>{l}</button>)}</nav><button data-testid="rules-button" onClick={()=>setRules(true)} className="pixel-button ghost">完整规则 ↗</button></div></header><nav className="mobile-nav md:hidden">{links.map(([v,l])=><button key={v} onClick={()=>setView(v)} className={view===v?'active':''}>{l}</button>)}</nav></>}

function Home({start,setView}:{start:()=>void;setView:(v:View)=>void}){return <><section className="mx-auto grid max-w-7xl gap-10 px-5 pb-14 pt-12 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:pt-16"><div><div className="status-chip"><i/>距离老板牌局 · 建议 15 分钟路径</div><h1 className="mt-6 text-5xl font-black leading-[1.06] sm:text-7xl">快速会打，<br/><span className="text-[var(--gold)]">体面上桌。</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300">零基础认识真实规则，用不作弊的 AI 牌友练一整副牌。每手有解释、每局有证据复盘，学会配合，也学会让牌桌气氛舒服。</p><div className="mt-8 flex flex-wrap gap-4"><button data-testid="start-game" onClick={()=>setView('lesson')} className="pixel-button primary">开始 15 分钟特训 ▶</button><button onClick={()=>setView('memory')} className="pixel-button secondary">先练 2 分钟记牌</button></div><div className="mt-8 flex flex-wrap gap-5 text-xs font-bold text-slate-400"><span>✓ 双副牌 108 张</span><span>✓ 4 位 AI 牌友</span><span>✓ 完整事件回放</span></div></div><Mission start={start} setView={setView}/></section><section className="border-y-2 border-slate-700 bg-slate-900/60"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-px bg-slate-700 md:grid-cols-4">{[['15','分钟救急路线'],['12','种核心牌型'],['108','张唯一牌 ID'],['0','暗号与作弊']].map(([n,l])=><div className="bg-[var(--ink)] p-6 text-center" key={l}><strong className="text-3xl text-[var(--mint)]">{n}</strong><small className="mt-1 block text-xs text-slate-400">{l}</small></div>)}</div></section></>}
function Mission({start,setView}:{start:()=>void;setView:(v:View)=>void}){return <div className="relative"><div className="training-card border-4 border-slate-950 bg-[var(--paper)] p-5 text-[var(--ink)] shadow-[9px_9px_0_var(--gold)] sm:p-7"><div className="flex items-end justify-between border-b-4 border-[var(--ink)] pb-4"><div><small className="font-black tracking-[.2em] text-slate-500">TODAY&apos;S MISSION</small><h2 className="mt-1 text-2xl font-black">选择上桌速度</h2></div><span className="boss-badge">老板局</span></div><div className="mt-5 space-y-3"><Track time="15 MIN" title="救急上桌" desc="先会出牌，不让全桌等你" onClick={()=>setView('lesson')} active/><Track time="30 MIN" title="默契搭档" desc="读懂搭档，不抢无谓的牌权" onClick={start}/><Track time="60 MIN" title="完整陪练" desc="规则、记牌与完整实战" onClick={start}/></div><p className="mt-5 border-t-2 border-dashed border-slate-300 pt-4 text-xs leading-6 text-slate-500">牌技分与社交分分开计算。系统不会奖励故意输牌、暗示牌情或串通。</p></div></div>}
function Track({time,title,desc,onClick,active}:{time:string;title:string;desc:string;onClick:()=>void;active?:boolean}){return <button onClick={onClick} className={`track-row ${active?'active':''}`}><span className="time-chip">{time}</span><span className="text-left"><b className="block">{title}</b><small className="text-slate-500">{desc}</small></span><span className="ml-auto">→</span></button>}

function Lesson({lesson,setLesson,start}:{lesson:number;setLesson:(n:number)=>void;start:()=>void}){const current=LESSONS[lesson];return <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow">15 MIN · CRASH COURSE</p><h1 className="text-3xl font-black sm:text-5xl">救急上桌路线</h1></div><b className="text-[var(--gold)]">{lesson+1} / 4</b></div><div className="grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="space-y-2">{LESSONS.map((l,i)=><button key={l.n} onClick={()=>setLesson(i)} className={`lesson-row ${lesson===i?'active':''}`}><b>{l.n}</b><span><strong>{l.t}</strong><small>{l.m}</small></span></button>)}</aside><article className="paper-panel min-h-[440px]"><p className="eyebrow dark">LESSON {current.n}</p><h2 className="mt-2 text-3xl font-black">{current.t}</h2><p className="mt-2 text-slate-600">{current.d}</p><LessonVisual index={lesson}/><div className="mt-8 flex justify-between"><button disabled={!lesson} onClick={()=>setLesson(Math.max(0,lesson-1))} className="pixel-button dark disabled:opacity-30">← 上一节</button>{lesson<3?<button onClick={()=>setLesson(lesson+1)} className="pixel-button coral">下一节 →</button>:<button data-testid="lesson-start-game" onClick={start} className="pixel-button coral">进入 AI 实战 ▶</button>}</div></article></div></section>}
function LessonVisual({index}:{index:number}){const content=[<div key="types" className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['4','单张'],['44','对子'],['44455','三带二'],['♥3…7','同花顺']].map(([p,n])=><div className="mini-card" key={n}><b>{p}</b><span>{n}</span></div>)}</div>,<div key="flow" className="flow-strip"><b>领出</b><i>→</i><b>压牌 / 过牌</b><i>→</i><b>全员过</b><i>→</i><b>接风</b></div>,<div key="boss" className="grid gap-3 sm:grid-cols-3">{[['01','先想好再摸牌','减少停顿'],['02','夸具体的一手','不尬吹'],['03','正常竞技','不喂牌、不暗示']].map(x=><div className="tip-card" key={x[0]}><b>{x[0]}</b><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div>,<div key="memory" className="grid grid-cols-3 gap-2">{['大王','小王','级牌','A','2','炸弹','搭档余牌','对手余牌','本圈牌权'].map(x=><div className="memory-tile static" key={x}>{x}</div>)}</div>];return <div className="lesson-visual">{content[index]}</div>}

function Game({state,selected,setSelected,onPlay,onPass,coach,restart,nextDeal,setView}:{state:GameState;selected:string[];setSelected:(v:string[])=>void;onPlay:()=>void;onPass:()=>void;coach:string;restart:()=>void;nextDeal:()=>void;setView:(v:View)=>void}){const me=state.players[0],last=state.lastPlay,analysis=analyzeStyle(state);return <section className="mx-auto max-w-7xl px-3 py-5 sm:px-6"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">AI PRACTICE · 第 {state.roundNo} 副 / 第 {state.trickNo} 圈</p><h1 className="text-2xl font-black">打 {RANK_LABEL[state.level]} · 你与小顾一队</h1></div><div className="flex gap-2"><span className="mode-chip">提示 ON</span><button onClick={restart} className="pixel-button ghost smallbtn">新比赛</button></div></div><div className="game-shell"><Opponent player={state.players[2]} active={state.turn===2} top/><Opponent player={state.players[3]} active={state.turn===3} side="left"/><Opponent player={state.players[1]} active={state.turn===1} side="right"/><div className="table-center"><div className="last-play">{last?<><small>{state.players[last.seat].name} · {comboName(last.combo)}</small><div className="played-cards">{last.combo.cards.map(c=><CardView card={c} key={c.id} compact/>)}</div></>:<><b>新一圈</b><small>领出任意合法牌型</small></>}</div><div className="turn-badge">{state.phase==='finished'?'本副结束':state.turn===0?'轮到你':'AI 思考中…'}</div></div><div className="self-seat"><div className="coach-bubble"><span>AI 教练</span><p>{coach}</p></div><div className="hand" aria-label="你的手牌">{me.hand.map(card=><CardView key={card.id} card={card} selected={selected.includes(card.id)} onClick={()=>setSelected(selected.includes(card.id)?selected.filter(x=>x!==card.id):[...selected,card.id])}/>)}</div><div className="action-bar"><button onClick={onPass} disabled={state.turn!==0||!last} className="pixel-button dark">过牌</button><button data-testid="play-button" onClick={onPlay} disabled={state.turn!==0||!selected.length} className="pixel-button coral">出牌 ({selected.length})</button></div></div></div>{state.phase==='finished'&&<div className="result-modal"><div className="paper-panel max-w-lg"><p className="eyebrow dark">ROUND COMPLETE</p><h2 className="text-3xl font-black">{resultLabel(state)}</h2><div className="score-split"><div><b>{analysis.metrics.score}</b><span>牌技分</span></div><div><b>{analysis.socialScore}</b><span>社交分</span></div></div><h3>{analysis.title}</h3>{analysis.advice.map(a=><p key={a}>• {a}</p>)}<div className="mt-5 flex gap-3">{state.matchWinner===null&&<button onClick={nextDeal} className="pixel-button coral">贡还牌并继续</button>}<button onClick={()=>setView('replay')} className="pixel-button dark">查看回放</button></div></div></div>}</section>}
function Opponent({player,active,top,side}:{player:GameState['players'][number];active:boolean;top?:boolean;side?:'left'|'right'}){return <div className={`opponent ${top?'top':''} ${side||''} ${active?'active':''}`}><div className="avatar">{player.name[0]}</div><b>{player.name}{player.role==='boss'?' · 老板':''}</b><span>{player.finished?`第 ${player.finished} 名`:`${player.hand.length} 张`}</span></div>}
function CardView({card,selected,compact,onClick}:{card:Card;selected?:boolean;compact?:boolean;onClick?:()=>void}){const red=card.suit==='H'||card.suit==='D',inside=<><span>{cardLabel(card)}</span>{card.suit!=='J'&&<i>{card.suit==='S'?'♠':card.suit==='H'?'♥':card.suit==='C'?'♣':'♦'}</i>}</>;return compact?<div aria-label={cardLabel(card)} className={`playing-card ${red?'red':''} compact`}>{inside}</div>:<button aria-label={cardLabel(card)} aria-pressed={selected} onClick={onClick} className={`playing-card ${red?'red':''} ${selected?'selected':''}`}>{inside}</button>}

function hash(text:string){let h=2166136261;for(const ch of text){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function shuffled<T>(values:T[],key:string){return [...values].sort((a,b)=>hash(`${key}:${String(a)}`)-hash(`${key}:${String(b)}`))}
function Memory(){const base=['大王','小王','红桃级牌','黑桃 A','方片 2','梅花 K','六张炸弹','搭档剩 5 张','右手边剩 2 张'];const [round,setRound]=useState(1),[seed]=useState(()=>Date.now()%1000003),[phase,setPhase]=useState<'show'|'recall'|'done'>('show'),[picked,setPicked]=useState<string[]>([]),[remaining,setRemaining]=useState(10),[attempts,setAttempts]=useState<{score:number;round:number}[]>([]);const items=shuffled(base,`grid-${seed}-${round}`),target=shuffled(base,`target-${seed}-${round}`).slice(0,3),score=target.filter(x=>picked.includes(x)).length;useEffect(()=>{const id=setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem('gd-memory-v2')||'[]');if(Array.isArray(saved)&&saved.length){setAttempts(saved);setRound(Math.max(...saved.map((a:{round:number})=>a.round))+1)}}catch{localStorage.removeItem('gd-memory-v2')}},0);return()=>clearTimeout(id)},[]);useEffect(()=>{if(phase!=='show')return;const id=setInterval(()=>setRemaining(v=>{if(v<=1){clearInterval(id);setPhase('recall');return 0}return v-1}),1000);return()=>clearInterval(id)},[phase,round]);const submit=()=>{setPhase('done');const next=[...attempts,{score,round}];setAttempts(next);localStorage.setItem('gd-memory-v2',JSON.stringify(next))};return <section className="mx-auto max-w-5xl px-5 py-10 sm:px-8"><p className="eyebrow">MEMORY GRID · 真实牌局迁移</p><h1 className="text-4xl font-black">九宫格记关键牌</h1><p className="mt-3 text-slate-300">每轮牌面、位置和目标都独立洗牌，并保存准确率。只记会改变真实决策的 9 个信息。</p><div className="mt-8 paper-panel"><div className="flex items-center justify-between gap-3"><b data-testid="memory-prompt">{phase==='show'?`观察 ${remaining} 秒：记住位置`:phase==='recall'?`请找出：${target.join('、')}`:`本轮得分 ${score} / 3`}</b><span className="mode-chip dark">间隔复习 · 第 {round} 轮</span></div><div className="memory-grid">{items.map((x,i)=><button data-testid={`memory-${i}`} disabled={phase==='show'||phase==='done'} onClick={()=>setPicked(picked.includes(x)?picked.filter(v=>v!==x):[...picked,x])} className={`memory-tile ${picked.includes(x)?'picked':''}`} key={x}>{phase==='recall'&&!picked.includes(x)?`${i+1}`:x}</button>)}</div>{phase==='show'?<button data-testid="memory-hide" onClick={()=>setPhase('recall')} className="pixel-button coral">提前遮住并开始回忆</button>:phase==='recall'?<button data-testid="memory-submit" onClick={submit} className="pixel-button coral">提交答案</button>:<div><p className="mt-4 text-slate-600">{score===3?'全对！下一轮会更换位置和目标。':'回到真实牌局时，优先扫一遍王、级牌、A 和 2。'} 累计准确率：{attempts.length?Math.round(attempts.reduce((n,a)=>n+a.score,0)/(attempts.length*3)*100):0}%</p><button onClick={()=>{setRound(round+1);setPhase('show');setRemaining(10);setPicked([])}} className="pixel-button dark mt-3">进入下一轮</button></div>}</div></section>}

function Replay({history}:{history:GameState[]}){const [chosen,setChosen]=useState<number|null>(history.length?0:null),[cursor,setCursor]=useState(0),deck=new Map(createDeck().map(c=>[c.id,c])),game=chosen===null?null:history[chosen],events=game?.events??[],event=events[cursor];const label=(type:string)=>({deal:'发牌',play:'出牌',pass:'过牌',trick:'新一圈',finish:'出完',round:'贡还牌'}[type]??type);return <section className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p className="eyebrow">MATCH ARCHIVE · 本机保存</p><h1 className="text-4xl font-black">完整对局回放</h1><p className="mt-3 text-slate-300">逐事件查看座位、牌张、圈次与分析证据；损坏记录会在载入时安全清除。</p><div className="mt-8 grid gap-5 lg:grid-cols-[340px_1fr]"><div className="space-y-3">{history.length?history.map((g,i)=><button onClick={()=>{setChosen(i);setCursor(0)}} className={`replay-row ${chosen===i?'active':''}`} key={g.seed}><span className="time-chip">#{history.length-i}</span><span><b>打 {RANK_LABEL[g.level]} · {new Date(g.createdAt||0).toLocaleDateString('zh-CN')}</b><small>{g.events.length} 个事件 · {g.ruleVersion}</small></span></button>):<div className="empty-state"><b>还没有完成的对局</b><p>完成第一副 AI 实战后，这里会出现逐手事件与牌风报告。</p></div>}</div>{game&&event&&<article className="paper-panel"><div className="flex justify-between"><p className="eyebrow dark">EVENT {cursor+1} / {events.length}</p><b>{resultLabel(game)}</b></div><h2 className="mt-3 text-3xl font-black">{label(event.type)}{event.seat!==undefined?` · ${game.players[event.seat].name}`:''}</h2><p className="mt-2 text-sm text-slate-500">{event.note||'该动作已通过规则引擎校验'}</p><div className="my-8 flex min-h-24 items-center justify-center">{event.cardIds?.length?<div className="played-cards">{event.cardIds.map(id=>deck.get(id)).filter(Boolean).map(c=><CardView card={c!} key={c!.id} compact/>)}</div>:<span className="text-sm text-slate-400">本事件没有牌张移动</span>}</div><div className="flex justify-between"><button disabled={!cursor} onClick={()=>setCursor(cursor-1)} className="pixel-button dark">← 上一步</button><button disabled={cursor>=events.length-1} onClick={()=>setCursor(cursor+1)} className="pixel-button coral">下一步 →</button></div><div className="mt-7 border-t-2 border-dashed border-slate-300 pt-5"><b>{analyzeStyle(game).title}</b>{analyzeStyle(game).advice.slice(0,2).map(a=><p className="mt-2 text-xs text-slate-600" key={a}>• {a}</p>)}</div></article>}</div></section>}

function Rulebook({close}:{close:()=>void}){const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null,escape=(e:KeyboardEvent)=>{if(e.key==='Escape')close()};document.addEventListener('keydown',escape);closeRef.current?.focus();return()=>{document.removeEventListener('keydown',escape);previous?.focus()}},[close]);return <div className="drawer-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close()}}><aside className="rule-drawer" role="dialog" aria-modal="true" aria-label="完整规则"><div className="sticky top-0 flex items-center justify-between border-b-4 border-[var(--ink)] bg-[var(--paper)] py-4"><div><p className="eyebrow dark">RULEBOOK · V1.0</p><h2 className="text-2xl font-black">竞技掼蛋教学规则</h2></div><button ref={closeRef} aria-label="关闭规则" data-testid="close-rules" onClick={close} className="close-btn">×</button></div><p className="my-5 border-2 border-amber-400 bg-amber-50 p-3 text-xs leading-6 text-amber-900">默认规则以 2022 竞技掼蛋竞赛规则为基线。地区牌桌对顺子、同花顺和贡牌可能有变体，上桌前先问一句“按哪边的规矩”。</p>{RULES.map(([t,d])=><section className="rule-section" key={t}><h3>{t}</h3><p>{d}</p></section>)}<section className="rule-section"><h3>11 · 牌桌礼仪</h3><p>不催牌、不偷看、不暗示隐藏信息。夸具体好牌，失误不甩锅。陪老板玩得开心来自节奏、配合与尊重，而不是串通或固定输牌。</p></section></aside></div>}
