export type Locale='zh'|'en';

export type LessonStep={scene:string;prompt:string;options:[string,...string[]];correct:number;explain:string;wrong:string};
export type OnboardingCopy={
  languageLabel:string;
  languageSwitch:string;
  nav:{home:string;lesson:string;memory:string;replay:string;rules:string};
  home:{status:string;headline:string;headlineAccent:string;intro:string;start:string;memory:string;onlineContinue:string;onlineBeta:string;onlineLocked:string;proof:[string,string,string];stats:[[string,string],[string,string],[string,string],[string,string]]};
  mission:{title:string;badge:string;castAlt:string;castTitle:string;castNote:string;tracks:[{time:string;title:string;description:string},{time:string;title:string;description:string},{time:string;title:string;locked:string;unlocked:string}];ethics:string};
  course:{eyebrow:string;title:string;intro:string;mastered:string;locked:string;mistakes:string;correct:string;retry:string;nextQuestion:string;complete:string;checklistTitle:string;checklist:string[];previous:string;next:string;start:string};
  lessons:{n:string;t:string;d:string;m:string;steps:LessonStep[]}[];
  rules:{dialogLabel:string;title:string;close:string;notice:string;sections:[string,string][];etiquetteTitle:string;etiquette:string};
  footer:{tagline:string;voiceLabel:string;localAgent:string;remoteAgent:string;deviceVoice:string;elevenLabsVoice:string;signedIn:string;googleClaim:string;export:string;remove:string;logout:string;github:string;support:string;removeConfirm:string;removeError:string;logoutError:string};
  share:{button:string;footer:string;title:string;text:string;shared:string;copied:string;failed:string};
  support:{dialogLabel:string;close:string;title:string;body:string};
  login:{success:string;cancelled:string;error:string;close:string};
};

const zh:OnboardingCopy={
  languageLabel:'语言',languageSwitch:'EN',
  nav:{home:'训练大厅',lesson:'极速课程',memory:'记牌九宫格',replay:'对局档案',rules:'完整规则 ↗'},
  home:{status:'距离陈总牌局 · 建议 15 分钟路径',headline:'快速会打，',headlineAccent:'体面上桌。',intro:'零基础认识竞技规则，用不作弊的 AI 牌友练一整副牌。关键回合有提示、每局有证据复盘，学会配合，也学会让牌桌气氛舒服。',start:'开始 15 分钟特训 ▶',memory:'先练 2 分钟记牌',onlineContinue:'继续真人牌局 ▶',onlineBeta:'在线四人匹配 BETA',onlineLocked:'完成基础验证后匹配',proof:['✓ 双副牌 108 张','✓ 3 位 AI 牌友 · 四人牌桌','✓ 完整事件回放'],stats:[['15','分钟救急路线'],['10','类核心牌型'],['108','张唯一牌 ID'],['0','暗号与作弊']]},
  mission:{title:'选择训练入口',badge:'陈总局',castAlt:'陈总、小顾、林姐和学员的像素风训练角色',castTitle:'今晚训练桌',castNote:'虚构角色 · 陈总控场 / 小顾协作 / 林姐突围',tracks:[{time:'15 MIN',title:'救急上桌',description:'14 道必会判断，答对才解锁实战'},{time:'2 MIN',title:'记牌热身',description:'已见牌减法与九宫关键牌余量盘'},{time:'整副牌',title:'AI 完整陪练',locked:'先完成基础验证再进入',unlocked:'进入 108 张四人牌桌'}],ethics:'牌技分与社交分分开计算。系统不会奖励故意输牌、暗示牌情或串通。'},
  course:{eyebrow:'15 MIN · MASTERY COURSE',title:'救急上桌路线',intro:'每题必须答对才解锁下一步。答错会解释原因，不扣分、不跳过。',mastered:'已掌握',locked:'待解锁',mistakes:'错题',correct:'✓ 判断正确',retry:'再想一下',nextQuestion:'下一题 →',complete:'✓ 本节能力验证完成',checklistTitle:'上桌前能力清单',checklist:['✓ 认出核心牌型','✓ 合法领出、跟牌与过牌','✓ 知道何时接风','✓ 回应陈总时具体、不尬吹、不泄牌','✓ 用公开出牌对王、A、级牌做减法'],previous:'← 上一节',next:'下一节 →',start:'进入 AI 实战 ▶'},
  lessons:[
    {n:'01',t:'一眼认牌型',d:'单张、对子到炸弹，先学会“这是什么”',m:'4 分钟',steps:[
      {scene:'牌面：4♠ 4♥ 4♣ 5♠ 5♥',prompt:'这五张是什么牌型？',options:['顺子','三带二','钢板'],correct:1,explain:'三张同点牌带一对，叫“三带二”。',wrong:'先找“三张相同 + 一对相同”，它不是连续点数。'},
      {scene:'牌面：3♠ 3♥ 4♠ 4♥ 5♠ 5♥',prompt:'三个连续对子叫什么？',options:['三连对（木板）','二连三（钢板）','六张炸弹'],correct:0,explain:'33、44、55 是三个连续对子，也叫木板。',wrong:'每个点数只有两张；钢板要求两个连续的三张。'},
      {scene:'牌面：7♠ 7♥ 7♣ 8♠ 8♥ 8♣',prompt:'两个连续三张叫什么？',options:['三带二','三连对（木板）','二连三（钢板）'],correct:2,explain:'777、888 是两个连续三张，也叫钢板。',wrong:'每个点数有三张，而且只有两个连续点数。'},
      {scene:'牌面：♥3 ♥4 ♥5 ♥6 ♥7',prompt:'同一花色的五张顺子是什么？',options:['普通顺子','同花顺','五张炸弹'],correct:1,explain:'五张连续且同一花色，是能压普通牌型的同花顺。',wrong:'既要看连续点数，也要看五张是否同一花色。'},
    ]},
    {n:'02',t:'轮到我该做什么',d:'领出、压牌、过牌和接风',m:'4 分钟',steps:[
      {scene:'新一圈，你拥有 8♠ 8♥ 和 9♣。',prompt:'你要主动领出一对，选择哪项？',options:['出 8♠ 8♥','出 8♠ 8♥ 9♣','过牌'],correct:0,explain:'领出可以选择任意合法牌型；88 是合法对子。',wrong:'领出不能过牌；两张 8 加一张 9 也不是合法组合。'},
      {scene:'当前打 2。陈总刚出 7♠ 7♥，你有 9♠ 9♥。',prompt:'想取得牌权，应该怎么做？',options:['出 9♠ 9♥','只出 9♠','出 6♠ 6♥'],correct:0,explain:'当前级牌是 2；99 按普通点数比较，可以压 77。',wrong:'跟对子必须仍出对子，而且点数要更大；本题级牌是 2。'},
      {scene:'当前打 2。林姐刚出 A♠ A♥，你只有 9♠ 9♥，没有炸弹。',prompt:'这时最稳妥的合法动作是？',options:['出 9♠ 9♥','过牌','拆一张 9'],correct:1,explain:'当前级牌是 2；普通 99 压不过 AA，过牌是合法决策。',wrong:'本题级牌是 2，不能用更小的普通对子或不同张数去压 AA。'},
      {scene:'小顾最后一手出完，陈总和林姐都过牌。',prompt:'下一圈通常由谁“接风”领出？',options:['小顾的搭档，也就是你','陈总','随机玩家'],correct:0,explain:'最后一手无人压制时，由出完者的搭档接风。',wrong:'接风优先把领出权交给已经出完玩家的搭档。'},
    ]},
    {n:'03',t:'老板局不冷场',d:'少停顿、会回应、不给暗号',m:'3 分钟',steps:[
      {scene:'陈总用一手小牌送搭档出完，同时保住了炸弹。',prompt:'哪句回应具体、自然，又不显得奉承？',options:['陈总英明！您怎么打都对！','这手把牌权送得很准。','我知道您手里还有炸弹。'],correct:1,explain:'夸具体决策，比空泛吹捧舒服；也没有暗示隐藏信息。',wrong:'避免尬吹和泄露你推测到的隐藏牌，只评价公开动作。'},
      {scene:'搭档小顾误拆了一对，桌面气氛有点僵。',prompt:'你怎么回应最合适？',options:['你怎么连这个都不会？','没事，下一圈我来补位。','陈总，这局都是他的问题。'],correct:1,explain:'不甩锅，给出下一步配合，牌桌会更轻松。',wrong:'公开责怪搭档只会让气氛更僵，也破坏后续配合。'},
      {scene:'轮到你，大家已经等了十几秒。',prompt:'你还没看清牌型，应该怎么说？',options:['马上，我先确认是不是钢板。','别催，我第一次玩。','随便出一张算了。'],correct:0,explain:'短句说明你正在确认什么，然后尽快行动。',wrong:'不需要顶嘴，也不要为了快而跳过合法性判断。'},
    ]},
    {n:'04',t:'九宫格记关键牌',d:'只记王、级牌、A、2 和炸弹材料',m:'4 分钟',steps:[
      {scene:'公开出牌：大王、小王、A♠、A♥、红桃级牌。两副牌共有 4 张王。',prompt:'现在还没出现的王有几张？',options:['1 张','2 张','3 张'],correct:1,explain:'4 张王已出现 2 张，还剩 2 张。',wrong:'两副牌共有大王 2 张、小王 2 张，共 4 张王。'},
      {scene:'桌面已出现 A♠、A♥。两副牌共有 8 张 A。',prompt:'未出现的 A 还有几张？',options:['4 张','6 张','8 张'],correct:1,explain:'8 − 2 = 6。记牌是从真实公开事件做减法。',wrong:'每副牌四张 A，两副共 8 张；桌面已出现 2 张。'},
      {scene:'当前打 6，桌面已出现一张红桃 6。两副牌共有 8 张点数 6。',prompt:'未出现的级牌 6 还有几张？',options:['6 张','7 张','8 张'],correct:1,explain:'8 − 1 = 7。优先记王、级牌、A、2 和炸弹材料。',wrong:'两副牌每个普通点数共有 8 张；刚刚只出现 1 张。'},
    ]},
  ],
  rules:{dialogLabel:'完整规则',title:'竞技掼蛋教学规则',close:'关闭规则',notice:'默认规则以 2022 竞技掼蛋竞赛规则为基线。地区牌桌对顺子、同花顺和贡牌可能有变体，上桌前先问一句“按哪边的规矩”。',sections:[
    ['01 · 目标与搭档','四人使用两副牌，共 108 张。对家是固定搭档。每副按出完顺序定头游、二游、三游、末游；搭档双上升 3 级，头游三游升 2 级，头游末游升 1 级。'],['02 · 牌点大小','普通单牌由 2 到 A；当前级牌高于 A，低于小王、大王。红桃级牌是“逢人配”，在多张组合里可代替 2—A，但不能变成王。'],['03 · 基本牌型','单张、对子、三张、三带二、五张顺子、三连对（木板）、二连三（钢板）。普通牌型只能用相同类型、相同张数且点数更大的牌压制。'],['04 · 炸弹','四至八张及以上同点牌为炸弹；炸弹张数越多越大，同张数比较点数。五张同花顺高于五张炸弹、低于六张及以上炸弹；四王炸最大。炸弹可压普通牌。'],['05 · 出牌与过牌','领出者可出任意合法牌型。其余玩家依次压牌或过牌；若后续有人改变了最大牌，之前过牌者再次轮到时仍可压牌。其余玩家连续过牌后，最后出牌者获得下一圈领出权。'],['06 · 接风','某玩家最后一手无人压制且已经出完时，由其搭档“接风”领出；若搭档也已出完，则按座次交给下一位仍有手牌的玩家。'],['07 · 进贡与还贡','上一副末游向头游进贡除红桃级牌外的最大牌；双下时两名下家分别进贡，头游取得较大贡牌，该贡牌的进贡者先出。收贡者须还实际牌点不高于 10 的牌（级牌不能作为低点还出）。单贡者持两张大王，或双贡双方合计持两张大王时抗贡。'],['08 · 双上与报牌','同队取得头游、二游即“双上”，本副立即自然结束，另两家双下。手牌剩 10 张或更少时应按牌桌约定报牌，训练桌会始终显示每位玩家的剩余张数。'],['09 · 升级与过 A','双方从 2 起级，双上升 3 级、头游三游升 2 级、头游末游升 1 级。正在打 A 的一方必须取得头游且搭档不能是末游才算过 A；头游末游则继续打 A。'],['10 · 首出与牌桌变体','首副由随机座位先出；后续按进贡结果或抗贡规则确定。不同地区对顺子、同花顺展示、报牌时点可能不同，开桌前应确认采用 2022 竞技规则还是本地变体。']],etiquetteTitle:'11 · 牌桌礼仪',etiquette:'不催牌、不偷看、不暗示隐藏信息。夸具体好牌，失误不甩锅。陪老板玩得开心来自节奏、配合与尊重，而不是串通或固定输牌。'},
  footer:{tagline:'牌技有输赢，牌品没有捷径。',voiceLabel:'语音',localAgent:'本地规则',remoteAgent:'兼容大模型优先',deviceVoice:'设备语音',elevenLabsVoice:'ElevenLabs 优先',signedIn:'已登录',googleClaim:'Google 登录并认领进度',export:'导出数据',remove:'删除训练数据',logout:'退出登录',github:'GitHub 开源',support:'☕ 支持项目',removeConfirm:'确认删除当前云端资料、全部牌局，以及此设备上的训练进度？此操作无法撤销。',removeError:'删除失败，请稍后重试。',logoutError:'退出失败，请稍后重试。'},
  share:{button:'分享给牌友 ↗',footer:'分享本站',title:'GuanDan Lab · 掼蛋实验室',text:'零基础学掼蛋：规则课、与 3 位 AI 牌友进行四人陪练、记牌训练和完整回放。',shared:'分享完成',copied:'链接已复制',failed:'暂时无法分享，请复制浏览器地址'},
  support:{dialogLabel:'支持开源项目',close:'关闭支持二维码',title:'请作者喝杯咖啡',body:'感谢支持持续完善规则测试、无障碍体验与免费训练。打赏完全自愿，不影响任何功能。'},
  login:{success:'Google 登录成功，训练进度已认领。',cancelled:'已取消 Google 登录。',error:'Google 登录失败，请稍后重试。',close:'关闭登录提示'},
};

const en:OnboardingCopy={
  languageLabel:'Language',languageSwitch:'中文',
  nav:{home:'Training Hall',lesson:'Crash Course',memory:'Memory Grid',replay:'Match Archive',rules:'Full Rules ↗'},
  home:{status:'Chen’s table is coming · take the 15-minute path',headline:'Learn fast,',headlineAccent:'play with grace.',intro:'Learn competitive Guan Dan from zero, then practise a full deal with fair AI players. Key turns include guidance and every match leaves an evidence-based replay.',start:'Start the 15-minute course ▶',memory:'Try a 2-minute memory drill',onlineContinue:'Continue live match ▶',onlineBeta:'Four-player matchmaking BETA',onlineLocked:'Finish the foundation check to match',proof:['✓ Two decks · 108 cards','✓ Three AI players · four seats','✓ Complete event replay'],stats:[['15','minute crash course'],['10','core hand types'],['108','uniquely tracked cards'],['0','signals or collusion']]},
  mission:{title:'Choose your training path',badge:'Chen’s table',castAlt:'Pixel-art training cast: Chen, Gu, Lin and the learner',castTitle:'Tonight’s practice table',castNote:'Fictional cast · Chen controls / Gu supports / Lin sheds fast',tracks:[{time:'15 MIN',title:'Get table-ready',description:'14 required decisions before practice unlocks'},{time:'2 MIN',title:'Memory warm-up',description:'Visible-card subtraction and a nine-cell key-card counter'},{time:'FULL DEAL',title:'Complete AI practice',locked:'Complete the foundation check first',unlocked:'Enter the 108-card table'}],ethics:'Card skill and social skill are scored separately. Deliberate losing, signalling and collusion are never rewarded.'},
  course:{eyebrow:'15 MIN · MASTERY COURSE',title:'Table-ready crash course',intro:'Answer every question correctly to unlock the next step. Mistakes get an explanation, never a penalty or skip.',mastered:'Mastered',locked:'Locked',mistakes:'Mistakes',correct:'✓ Correct',retry:'Try again',nextQuestion:'Next question →',complete:'✓ Lesson check complete',checklistTitle:'Ready-to-play checklist',checklist:['✓ Recognise the core hand types','✓ Lead, beat and pass legally','✓ Know when a partner inherits the lead','✓ Respond to Chen specifically without flattery or signals','✓ Count jokers, aces and level cards from public plays'],previous:'← Previous',next:'Next lesson →',start:'Enter AI practice ▶'},
  lessons:[
    {n:'01',t:'Recognise hand types',d:'From singles and pairs to bombs: first learn what you are looking at',m:'4 min',steps:[
      {scene:'Cards: 4♠ 4♥ 4♣ 5♠ 5♥',prompt:'What is this five-card hand?',options:['Straight','Full house','Tube'],correct:1,explain:'Three cards of one rank plus a pair form a full house.',wrong:'Look for three equal ranks plus one equal pair; the ranks are not consecutive.'},
      {scene:'Cards: 3♠ 3♥ 4♠ 4♥ 5♠ 5♥',prompt:'What are three consecutive pairs called?',options:['Plate (three pairs)','Tube (two triples)','Six-card bomb'],correct:0,explain:'33, 44 and 55 are three consecutive pairs, often called a plate.',wrong:'Each rank appears twice; a tube needs two consecutive triples.'},
      {scene:'Cards: 7♠ 7♥ 7♣ 8♠ 8♥ 8♣',prompt:'What are two consecutive triples called?',options:['Full house','Plate (three pairs)','Tube (two triples)'],correct:2,explain:'777 and 888 are two consecutive triples, often called a tube.',wrong:'Each rank appears three times and there are exactly two consecutive ranks.'},
      {scene:'Cards: ♥3 ♥4 ♥5 ♥6 ♥7',prompt:'What is a five-card straight in one suit?',options:['Straight','Straight flush','Five-card bomb'],correct:1,explain:'Five consecutive cards in one suit form a straight flush.',wrong:'Check both consecutive ranks and a shared suit.'},
    ]},
    {n:'02',t:'Know your legal move',d:'Leading, beating, passing and inheriting the lead',m:'4 min',steps:[
      {scene:'New trick. You hold 8♠ 8♥ and 9♣.',prompt:'You want to lead a pair. What do you play?',options:['8♠ 8♥','8♠ 8♥ 9♣','Pass'],correct:0,explain:'A leader may choose any legal hand type; 88 is a legal pair.',wrong:'The leader cannot pass, and a pair plus an unrelated card is not legal.'},
      {scene:'The level is 2. Chen played 7♠ 7♥; you hold 9♠ 9♥.',prompt:'How can you take control?',options:['Play 9♠ 9♥','Play only 9♠','Play 6♠ 6♥'],correct:0,explain:'With 2 as the level, the ordinary pair of nines beats sevens.',wrong:'You must answer a pair with a higher pair; the level card here is 2.'},
      {scene:'The level is 2. Lin played A♠ A♥; you only have 9♠ 9♥ and no bomb.',prompt:'What is the safest legal action?',options:['Play 9♠ 9♥','Pass','Split one 9'],correct:1,explain:'An ordinary pair of nines cannot beat aces, so passing is legal.',wrong:'A smaller pair or a different card count cannot beat the aces.'},
      {scene:'Gu played their final cards. Chen and Lin both pass.',prompt:'Who normally leads the next trick?',options:['Gu’s partner — you','Chen','A random player'],correct:0,explain:'When the final play is unbeaten, the finished player’s partner inherits the lead.',wrong:'The lead first passes to the partner of the player who went out.'},
    ]},
    {n:'03',t:'Keep the table comfortable',d:'Respond promptly, support your partner and never signal hidden cards',m:'3 min',steps:[
      {scene:'Chen used a small play to send a partner out while keeping a bomb.',prompt:'Which response is specific and natural?',options:['Brilliant! Everything you do is right!','That transferred the lead precisely.','I know you still have a bomb.'],correct:1,explain:'Praise the visible decision rather than flattering or revealing inferred information.',wrong:'Avoid empty flattery and hidden-card signals; comment only on public actions.'},
      {scene:'Gu accidentally split a pair and the table goes quiet.',prompt:'What is the best response?',options:['How can you not know that?','No problem — I’ll cover the next trick.','Chen, this loss is all their fault.'],correct:1,explain:'Do not assign blame; offer the next coordination step.',wrong:'Public blame makes the table tense and hurts the next decision.'},
      {scene:'It is your turn and everyone has waited more than ten seconds.',prompt:'You still need to identify the hand. What do you say?',options:['One moment — I’m checking whether this is a tube.','Stop rushing me; I’m new.','I’ll just throw any card.'],correct:0,explain:'Briefly say what you are checking, then act promptly.',wrong:'Do not snap at the table or sacrifice legality for speed.'},
    ]},
    {n:'04',t:'Remember key cards',d:'Track jokers, level cards, aces, twos and bomb material',m:'4 min',steps:[
      {scene:'Public cards: big joker, small joker, A♠, A♥ and the heart level card. Two decks contain four jokers.',prompt:'How many jokers are still unseen?',options:['1','2','3'],correct:1,explain:'Two of four jokers are visible, so two remain unseen.',wrong:'Two decks contain two big and two small jokers: four total.'},
      {scene:'A♠ and A♥ are visible. Two decks contain eight aces.',prompt:'How many aces are unseen?',options:['4','6','8'],correct:1,explain:'8 − 2 = 6. Card counting subtracts real public events.',wrong:'Each deck has four aces, so two decks have eight; two are visible.'},
      {scene:'The level is 6 and one heart 6 is visible. Two decks contain eight sixes.',prompt:'How many level-card sixes are unseen?',options:['6','7','8'],correct:1,explain:'8 − 1 = 7. Prioritise jokers, level cards, aces, twos and bomb material.',wrong:'Each ordinary rank appears eight times across two decks; one is visible.'},
    ]},
  ],
  rules:{dialogLabel:'Full rules',title:'Competitive Guan Dan teaching rules',close:'Close rules',notice:'The default baseline is the 2022 competitive Guan Dan rules. Regional tables may vary on straights, straight flushes and tribute, so confirm the table rules before play.',sections:[
    ['01 · Goal and teams','Four players use two decks (108 cards). Opposite seats are partners. Finishing order determines first through fourth place; a team finishing first and second advances three levels, first and third advances two, and first and fourth advances one.'],['02 · Rank order','Ordinary ranks run from 2 through ace. The current level card ranks above ace and below the small and big jokers. The heart level card is wild in multi-card combinations but cannot represent a joker.'],['03 · Basic hand types','Singles, pairs, triples, full houses, five-card straights, three consecutive pairs and two consecutive triples. Ordinary hands beat only the same type and card count at a higher rank.'],['04 · Bombs','Four or more equal-rank cards form a bomb; more cards beat fewer, and equal sizes compare rank. A five-card straight flush beats a five-card bomb but loses to bombs of six or more cards. Four jokers form the highest bomb.'],['05 · Playing and passing','A leader may play any legal type. Others beat it or pass in turn. A player who passed may still act if a later play changes the winning hand. After everyone else passes, the last player to play leads the next trick.'],['06 · Inheriting the lead','If a player goes out and their final play is unbeaten, their partner leads next. If that partner is also out, the lead moves by seat order to the next active player.'],['07 · Tribute and return','The previous last-place player gives their highest non-wild card to first place. With two losing players, both give tribute and the contributor of the higher tribute leads. Recipients return a card whose actual rank is at most 10; level cards are not low returns. A single contributor holding both big jokers resists tribute; with two contributors, their combined two big jokers also resist tribute.'],['08 · Team sweep and card count','Partners finishing first and second complete a team sweep and end the deal. Tables should agree when low card counts are announced; this trainer always displays remaining counts.'],['09 · Level advancement and passing ace','Teams start at level 2. A sweep advances three levels, first and third advances two, and first and fourth advances one. At ace, the side must finish first without its partner finishing last to pass ace.'],['10 · Opening lead and variants','The first deal uses a random leader; later deals use tribute or resistance rules. Regional conventions differ, so agree whether the 2022 competition baseline or a local variant applies.']],etiquetteTitle:'11 · Table etiquette',etiquette:'Do not rush, peek or signal hidden information. Praise specific public decisions and never blame a mistake. A pleasant table comes from pace, coordination and respect — not collusion or deliberate losing.'},
  footer:{tagline:'Cards have winners; table manners have no shortcut.',voiceLabel:'Voice',localAgent:'Local rules',remoteAgent:'Compatible model preferred',deviceVoice:'Device voice',elevenLabsVoice:'ElevenLabs preferred',signedIn:'Signed in',googleClaim:'Sign in with Google and claim progress',export:'Export data',remove:'Delete training data',logout:'Sign out',github:'GitHub source',support:'☕ Support the project',removeConfirm:'Delete this cloud profile, every saved match, and this device’s training progress? This cannot be undone.',removeError:'Could not delete your data. Please try again.',logoutError:'Could not sign out. Please try again.'},
  share:{button:'Share with a player ↗',footer:'Share this site',title:'GuanDan Lab',text:'Learn Guan Dan from zero with rules, fair AI practice, memory drills and complete replays.',shared:'Shared',copied:'Link copied',failed:'Sharing is unavailable; copy the browser address'},
  support:{dialogLabel:'Support the open-source project',close:'Close support QR code',title:'Buy the maintainer a coffee',body:'Your support funds rule tests, accessibility and free training. Tipping is always optional and never unlocks features.'},
  login:{success:'Google sign-in succeeded and your training progress is linked.',cancelled:'Google sign-in was cancelled.',error:'Google sign-in failed. Please try again.',close:'Dismiss sign-in notice'},
};

export const onboardingCopy:Record<Locale,OnboardingCopy>={zh,en};
