import { spawnSync } from 'node:child_process';
import { describe,expect,it } from 'vitest';
import { assessDeployment,formatDeploymentReport } from '../../scripts/doctor.mjs';

const core={SITE_URL:'https://guandan.mereith.com',SESSION_SECRET:'a-secure-random-session-secret-1234',DATABASE_PATH:'/data/guandan.sqlite',ONLINE_MATCHING_ENABLED:'0',PAID_PROVIDERS_ENABLED:'0',TRUST_PROXY:'0',AI_ALLOW_PRIVATE_BASE_URL:'0'};

describe('production deployment doctor',()=>{
  it('passes a safe core deployment without requiring optional providers',()=>{const report=assessDeployment(core);expect(report.ready).toBe(true);expect(report.summary.fail).toBe(0);expect(report.checks.find(check=>check.id==='tts')?.status).toBe('warn');expect(formatDeploymentReport(report)).not.toContain(core.SESSION_SECRET)});
  it('rejects missing core security and persistence configuration',()=>{const report=assessDeployment({SITE_URL:'http://public.example.com',SESSION_SECRET:'short',DATABASE_PATH:''});expect(report.ready).toBe(false);expect(report.checks.filter(check=>check.status==='fail').map(check=>check.id)).toEqual(expect.arrayContaining(['site_url','session','database']))});
  it('rejects partial OAuth, model and voice groups',()=>{const report=assessDeployment({...core,GOOGLE_CLIENT_ID:'client-only',PAID_PROVIDERS_ENABLED:'1',AI_API_KEY:'key-only',ELEVENLABS_VOICE_ID:'voice-only'});expect(report.ready).toBe(false);expect(report.checks.filter(check=>check.status==='fail').map(check=>check.id)).toEqual(expect.arrayContaining(['google','ai','tts']))});
  it('accepts complete public providers and a support link without echoing secrets',()=>{const env={...core,PAID_PROVIDERS_ENABLED:'1',PAID_PROVIDER_USER_DAILY_UNITS:'250',PAID_PROVIDER_GLOBAL_DAILY_UNITS:'5000',AI_BASE_URL:'https://models.openai.com/v1',AI_API_KEY:'private-model-key',AI_MODEL:'coach',ELEVENLABS_API_KEY:'private-voice-key',ELEVENLABS_VOICE_ID:'voice-id',ELEVENLABS_VOICE_ID_WANG:'voice-wang',ELEVENLABS_VOICE_ID_GU:'voice-gu',ELEVENLABS_VOICE_ID_LIN:'voice-lin',SUPPORT_URL:'https://support.mereith.com/me',GOOGLE_CLIENT_ID:'google-client',GOOGLE_CLIENT_SECRET:'google-secret',ONLINE_MATCHING_ENABLED:'1'},report=assessDeployment(env),json=JSON.stringify(report);expect(report.ready).toBe(true);expect(report.checks.find(check=>check.id==='budget')?.status).toBe('pass');expect(report.checks.find(check=>check.id==='ai')?.status).toBe('pass');expect(report.checks.find(check=>check.id==='tts')?.status).toBe('pass');for(const secret of [env.AI_API_KEY,env.ELEVENLABS_API_KEY,env.GOOGLE_CLIENT_SECRET])expect(json).not.toContain(secret)});
  it('fails closed when paid providers lack valid durable budgets',()=>{const missing=assessDeployment({...core,PAID_PROVIDERS_ENABLED:'1',AI_BASE_URL:'https://models.openai.com/v1',AI_API_KEY:'private-key',AI_MODEL:'coach'});expect(missing.checks.find(check=>check.id==='budget')?.status).toBe('fail');const invalid=assessDeployment({...core,PAID_PROVIDERS_ENABLED:'1',PAID_PROVIDER_USER_DAILY_UNITS:'100',PAID_PROVIDER_GLOBAL_DAILY_UNITS:'50',AI_BASE_URL:'https://models.openai.com/v1',AI_API_KEY:'private-key',AI_MODEL:'coach'});expect(invalid.ready).toBe(false)});
  it('rejects budgets smaller than a valid maximum-length speech request',()=>{const report=assessDeployment({...core,PAID_PROVIDERS_ENABLED:'1',PAID_PROVIDER_USER_DAILY_UNITS:'2',PAID_PROVIDER_GLOBAL_DAILY_UNITS:'2',ELEVENLABS_API_KEY:'voice-key',ELEVENLABS_VOICE_ID:'voice'});expect(report.checks.find(check=>check.id==='budget')?.status).toBe('fail');expect(report.ready).toBe(false)});
  it('blocks unsafe provider and support URLs while allowing an explicit trusted-LAN model warning',()=>{const budgets={PAID_PROVIDER_USER_DAILY_UNITS:'250',PAID_PROVIDER_GLOBAL_DAILY_UNITS:'5000'},unsafe=assessDeployment({...core,...budgets,PAID_PROVIDERS_ENABLED:'1',AI_BASE_URL:'http://127.0.0.1:11434/v1',AI_API_KEY:'key',AI_MODEL:'local',SUPPORT_URL:'http://support.example.com'});expect(unsafe.ready).toBe(false);expect(unsafe.checks.find(check=>check.id==='ai')?.status).toBe('fail');expect(unsafe.checks.find(check=>check.id==='support')?.status).toBe('fail');const lan=assessDeployment({...core,...budgets,PAID_PROVIDERS_ENABLED:'1',AI_BASE_URL:'http://127.0.0.1:11434/v1',AI_API_KEY:'key',AI_MODEL:'local',AI_ALLOW_PRIVATE_BASE_URL:'1'});expect(lan.ready).toBe(true);expect(lan.checks.find(check=>check.id==='ai')?.status).toBe('warn')});
  it('rejects committed example values instead of reporting them as production-ready',()=>{const report=assessDeployment({...core,PAID_PROVIDERS_ENABLED:'1',AI_BASE_URL:'https://your-provider.example/v1',AI_API_KEY:'replace-me',AI_MODEL:'your-model',ELEVENLABS_API_KEY:'replace-me',ELEVENLABS_VOICE_ID:'replace-me'});expect(report.ready).toBe(false);expect(report.checks.find(check=>check.id==='ai')?.status).toBe('fail');expect(report.checks.find(check=>check.id==='tts')?.status).toBe('fail')});
  it('uses the runtime-exact feature flag contract',()=>{const report=assessDeployment({...core,ONLINE_MATCHING_ENABLED:'1 ',PAID_PROVIDERS_ENABLED:'1 '});expect(report.ready).toBe(false);expect(report.checks.map(check=>check.id)).toEqual(expect.arrayContaining(['online_matching_enabled','paid_providers_enabled']));expect(report.checks.find(check=>check.id==='online')?.status).toBe('warn')});
  it.each(['/tmp/guandan.sqlite','/app/guandan.sqlite','guandan.sqlite',':memory:','/data/../tmp/guandan.sqlite'])('rejects a non-persistent Docker database path: %s',database=>{const report=assessDeployment({...core,DATABASE_PATH:database});expect(report.ready).toBe(false);expect(report.checks.find(check=>check.id==='database')?.status).toBe('fail')});
  it.each(['https://198.18.0.1/v1','https://[::]/v1','https://[::ffff:127.0.0.1]/v1'])('keeps provider URL blocking aligned for %s',baseUrl=>{const report=assessDeployment({...core,PAID_PROVIDERS_ENABLED:'1',AI_BASE_URL:baseUrl,AI_API_KEY:'private-model-key',AI_MODEL:'coach'});expect(report.ready).toBe(false);expect(report.checks.find(check=>check.id==='ai')?.status).toBe('fail')});
  it('does not confuse public domains beginning with IPv6 ULA letters for private hosts',()=>{const report=assessDeployment({...core,SITE_URL:'https://fcards.io',SUPPORT_URL:'https://fda.gov'});expect(report.ready).toBe(true);expect(report.checks.find(check=>check.id==='site_url')?.status).toBe('pass');expect(report.checks.find(check=>check.id==='support')?.status).toBe('pass')});
  it('rejects local/reserved public links and the documented English secret placeholder',()=>{const report=assessDeployment({...core,SITE_URL:'https://localhost.',SUPPORT_URL:'https://127.0.0.1/tip',SESSION_SECRET:'generate-at-least-32-random-bytes-with-a-password-manager'});expect(report.ready).toBe(false);expect(report.checks.filter(check=>check.status==='fail').map(check=>check.id)).toEqual(expect.arrayContaining(['site_url','session','support']))});
  it('provides actionable English text',()=>{const report=assessDeployment(core,{locale:'en'}),text=formatDeploymentReport(report,'en');expect(text).toContain('production configuration doctor');expect(text).toContain('Public URL');expect(text).not.toMatch(/[\u4e00-\u9fff]/u)});
  it('emits parseable secret-free JSON with an operational exit status',()=>{const secret='cli-random-session-secret-9876543210',result=spawnSync(process.execPath,['scripts/doctor.mjs','--json'],{cwd:process.cwd(),encoding:'utf8',env:{...process.env,...core,SESSION_SECRET:secret}});expect(result.status).toBe(0);expect(result.stderr).toBe('');expect(()=>JSON.parse(result.stdout)).not.toThrow();expect(JSON.parse(result.stdout).ready).toBe(true);expect(result.stdout).not.toContain(secret)});
});
