import { describe,expect,it } from 'vitest';
import { chooseAiMove,legalMoves,observe,safeAgentDecision,safeAgentMove } from '../../lib/game/ai';
import { rankPower } from '../../lib/game/cards';
import { parseCombo } from '../../lib/game/rules';
import { advanceLevel,legalPlay,newGame,nextRound,passTurn,playCards,upgradeSteps } from '../../lib/game/engine';

describe('game state machine',()=>{
  it('deals exactly 27 unique cards to every seat',()=>{const g=newGame(7);expect(g.players.map(p=>p.hand.length)).toEqual([27,27,27,27]);expect(new Set(g.players.flatMap(p=>p.hand.map(c=>c.id))).size).toBe(108)});
  it('chooses the first seat from the seed',()=>{expect(newGame(7).turn).toBe(3);expect(newGame(8).turn).toBe(0)});
  it('rejects cards not in hand and out-of-turn actions',()=>{const g=newGame(8);expect(legalPlay(g,1,[g.players[1].hand[0].id])).toMatchObject({ok:false});expect(legalPlay(g,0,['missing'])).toMatchObject({ok:false})});
  it('moves a played card exactly once and allows a valid pass',()=>{const g=newGame(8),id=g.players[0].hand[0].id;const after=playCards(g,0,[id]);expect(after.players[0].hand).toHaveLength(26);expect(after.events.find(e=>e.type==='play')?.cardIds).toEqual([id]);const passed=passTurn(after,1);expect(passed.turn).toBe(2)});
  it('keeps hidden hands and reconstructable seed out of an AI observation',()=>{const o=observe(newGame(8),1);expect(o.hand).toHaveLength(27);expect(o).not.toHaveProperty('players');expect(JSON.stringify(o.events)).not.toContain('seed')});
  it.each([[[0,2,1,3],3],[[0,1,2,3],2],[[0,1,3,2],1]])('computes upgrade result for %s',((order,steps)=>expect(upgradeSteps(order as never)).toBe(steps)));
  it('caps level at A',()=>expect(advanceLevel(13,3)).toBe(14));
  it('generates wildcard combinations, ten-card bombs and four jokers',async()=>{const g=newGame(8,2),all=g.players.flatMap(p=>p.hand),o=observe(g,0),jokers=all.filter(c=>c.suit==='J'),tens=all.filter(c=>c.rank===7),wild=all.filter(c=>c.rank===2&&c.suit==='H'),triplePair=[...all.filter(c=>c.rank===9).slice(0,2),...all.filter(c=>c.rank===10).slice(0,2),wild[0]];for(const hand of [jokers,[...tens,...wild],triplePair]){const custom={...o,hand,lastPlay:null},moves=legalMoves(custom),kinds=moves.map(m=>parseCombo(m.map(id=>hand.find(c=>c.id===id)!),2)?.kind);expect(kinds).toContain(hand.length===4?'jokerBomb':hand.length===10?'bomb':'triplePair')}const move=await safeAgentMove({name:'broken',choose:async()=>['not-a-card']},o);expect(move).not.toEqual(['not-a-card'])});
  it('reports whether a remote decision was accepted or locally replaced',async()=>{const o=observe(newGame(8),0),valid=legalMoves(o)[0];await expect(safeAgentDecision({name:'ok',choose:async()=>valid},o)).resolves.toEqual({move:valid,source:'llm'});const fallback=await safeAgentDecision({name:'bad',choose:async()=>['not-a-card']},o);expect(fallback.source).toBe('fallback');expect(fallback.move).not.toEqual(['not-a-card'])});
  it('runs seeded AI self-play with exact card conservation and no loop',()=>{for(let seed=1;seed<=60;seed++){let g=newGame(seed),moves=0;while(g.phase==='playing'&&moves++<3000){expect(g.players[g.turn].finished).toBeFalsy();const move=chooseAiMove(observe(g,g.turn));g=move?playCards(g,g.turn,move):passTurn(g,g.turn);const played=g.events.filter(e=>e.type==='play').flatMap(e=>e.cardIds||[]);expect(new Set(played).size).toBe(played.length);expect(g.players.reduce((n,p)=>n+p.hand.length,0)+played.length).toBe(108)}expect(g.phase,`seed ${seed}, moves ${moves}`).toBe('finished');expect(g.finishOrder).toHaveLength(4)}});
  it('starts a versioned next round with tribute and preserved card count',()=>{let g=newGame(4);g={...g,phase:'finished',finishOrder:[0,2,1,3],players:g.players.map((p,i)=>({...p,finished:i+1}))};const n=nextRound(g,5);expect(n.roundNo).toBe(2);expect(n.teamLevels[0]).toBe(5);expect(n.players.flatMap(p=>p.hand)).toHaveLength(108);expect(n.events.some(e=>e.note?.includes('贡'))).toBe(true)});
  it('gives the head winner the larger legal double tribute and lets that giver lead',()=>{let g=newGame(4);g={...g,phase:'finished',finishOrder:[0,2,1,3],players:g.players.map((p,i)=>({...p,finished:i+1}))};for(let seed=10;seed<200;seed++){const n=nextRound(g,seed),tributes=n.events.filter(e=>e.type==='round'&&e.cardIds?.length===2);if(tributes.length!==2)continue;const first=tributes[0].cardIds![0],second=tributes[1].cardIds![0],cards=n.players.flatMap(p=>p.hand),find=(id:string)=>cards.find(c=>c.id===id)!;expect(tributes[0].note).toContain('向0号位');expect(rankPower(find(first).rank,n.level)).toBeGreaterThanOrEqual(rankPower(find(second).rank,n.level));expect(find(first).suit==='H'&&find(first).rank===n.level).toBe(false);for(const e of tributes){const returned=find(e.cardIds![1]);expect(rankPower(returned.rank,n.level)).toBeLessThanOrEqual(10)}expect(n.turn).toBe(tributes[0].seat);return}throw new Error('no non-anti tribute seed found')});
  it('recognizes two big jokers split across double-down givers as anti-tribute',()=>{let g=newGame(4);g={...g,phase:'finished',finishOrder:[0,2,1,3],players:g.players.map((p,i)=>({...p,finished:i+1}))};for(let seed=1;seed<2000;seed++){const dealt=newGame(seed,5),big=dealt.players[1].hand.filter(c=>c.rank===16).length+dealt.players[3].hand.filter(c=>c.rank===16).length;if(big===2){const n=nextRound(g,seed);expect(n.events.at(-1)?.note).toContain('抗贡');expect(n.turn).toBe(0);return}}throw new Error('anti-tribute seed not found')});
  it('ends immediately on double-up',()=>{let g=newGame(8);g={...g,turn:2,leader:2,finishOrder:[0],players:g.players.map(p=>p.seat===0?{...p,finished:1}:p.seat===2?{...p,hand:[p.hand[0]]}:p)};const done=playCards(g,2,[g.players[2].hand[0].id]);expect(done.phase).toBe('finished');expect(done.finishOrder.slice(0,2)).toEqual([0,2]);expect(done.finishOrder).toHaveLength(4)});
  it('only passes A when the active A team gets head and partner is not last',()=>{let g=newGame(8,14);g={...g,levelOwner:0,teamLevels:[14,2],turn:0,leader:0,finishOrder:[2,1],players:g.players.map(p=>p.seat===2?{...p,finished:1}:p.seat===1?{...p,finished:2}:p.seat===0?{...p,hand:[p.hand[0]]}:p)};const done=playCards(g,0,[g.players[0].hand[0].id]);expect(done.matchWinner).toBe(0);expect(()=>nextRound(done,9)).toThrow('比赛已经结束');let fail=newGame(8,14);fail={...fail,levelOwner:0,teamLevels:[14,2],turn:3,leader:3,finishOrder:[0,1],players:fail.players.map(p=>p.seat===0?{...p,finished:1}:p.seat===1?{...p,finished:2}:p.seat===3?{...p,hand:[p.hand[0]]}:p)};expect(playCards(fail,3,[fail.players[3].hand[0].id]).matchWinner).toBeNull()});
  it('rejects pass actions after a deal is finished',()=>{const g={...newGame(8),phase:'finished' as const};expect(()=>passTurn(g,g.turn)).toThrow('已经结束')});
});
