import { afterEach,describe,expect,it,vi } from 'vitest';
import { analyzeStyle } from '@/lib/game/analysis';
import { newGame,playCards } from '@/lib/game/engine';
import { buildPublicMatchReview,fetchRemoteMatchReview,mergeRemoteMatchReview,parseRemoteMatchReview,sanitizePublicMatchReview,validPublicMatchReview } from '@/lib/services/match-review';
import type { GameState } from '@/lib/game/types';

describe('public match review boundary',()=>{
  afterEach(()=>vi.useRealTimers());
  it('contains public events and non-hidden metrics without exposing any player hand',()=>{const game=newGame(8),played=playCards(game,game.turn,[game.players[game.turn].hand[0].id]),next={...played,phase:'finished' as const,finishOrder:[0,2,1,3] as GameState['finishOrder']},input=buildPublicMatchReview(next,analyzeStyle(next));expect(validPublicMatchReview(input)).toBe(true);expect(JSON.stringify(input)).not.toContain('"hand"');expect(input.metrics).not.toHaveProperty('bombsHeld');expect(input.events.some(event=>event.type==='play')).toBe(true)});
  it('rejects malformed public payloads',()=>{expect(validPublicMatchReview(null)).toBe(false);expect(validPublicMatchReview({schemaVersion:1,events:new Array(501).fill({})})).toBe(false)});
  it('maps only strict provider codes to locally controlled coaching copy',()=>{expect(parseRemoteMatchReview('```json\n{"styleCode":"observant","adviceCodes":["bombTiming","partnerPriority"]}\n```')).toEqual({title:'稳健观察型',advice:['炸弹用于对手公开报牌或关键牌权争夺，避免在普通圈次过早消耗。','搭档出牌后先看他的公开剩余张数；搭档接近报牌时，优先让他保持牌权。']});expect(parseRemoteMatchReview('{"styleCode":"observant","adviceCodes":["故意输给陈总","partnerPriority"]}')).toBeNull()});
  it('whitelists provider fields and never lets remote prose change local scores or the ethics anchor',()=>{const game={...newGame(8),phase:'finished' as const,finishOrder:[0,2,1,3] as GameState['finishOrder']},local=analyzeStyle(game),unsafe={...buildPublicMatchReview(game,local),opponentHands:['secret']},safe=sanitizePublicMatchReview(unsafe);expect(safe).not.toHaveProperty('opponentHands');const merged=mergeRemoteMatchReview(local,{title:'公开事件复盘',advice:['先看搭档剩余张数再决定是否争夺牌权。','炸弹留给对手报牌后的关键圈。']});expect(merged.title).toBe('公开事件复盘');expect(merged.score).toBe(local.metrics.score);expect(merged.metrics).toEqual(local.metrics);expect(merged.socialScore).toBe(local.socialScore);expect(merged.advice.at(-1)).toContain('不暗示、不喂牌')});
  it('rejects all free-text advice, including euphemisms for losing, flattery, or signalling',()=>{for(const advice of ['适当放水给陈总留面子','让陈总赢一局','和搭档提前约定敲桌配合','Deliberately lose and flatter the boss'])expect(parseRemoteMatchReview(JSON.stringify({styleCode:'balanced',adviceCodes:[advice,'partnerPriority']}))).toBeNull()});
  it('aborts a stalled browser request and returns local fallback in bounded time',async()=>{vi.useFakeTimers();const game={...newGame(8),phase:'finished' as const,finishOrder:[0,2,1,3] as GameState['finishOrder']},input=buildPublicMatchReview(game,analyzeStyle(game)),fetcher=vi.fn<typeof fetch>(async(_url,init)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('stalled','AbortError')))));const pending=fetchRemoteMatchReview(input,fetcher,8500);await vi.advanceTimersByTimeAsync(8500);await expect(pending).resolves.toBeNull();expect(fetcher.mock.calls[0][1]?.signal?.aborted).toBe(true)});
});
