import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { POST } from '../../app/api/review/route';
import { openProgressDatabase,resetProgressDatabaseForTests,upsertSession } from '../../lib/services/progress-store';
import { resetProviderCircuitsForTests } from '../../lib/services/provider-guard';
import { createGuestSession,SESSION_COOKIE } from '../../lib/services/session';

const review={schemaVersion:1 as const,ruleVersion:'guandan-lab-1',level:8,roundNo:1,result:'我方胜',finishOrder:['你','小顾','王总','方总'],metrics:{opportunities:4,presses:2,bombsSpent:0,partnerYields:1,riskyLeads:0,score:82},score:82,socialScore:88,localTitle:'搭档优先型',localAdvice:['按公开事件复盘。'],events:[{sequence:1,type:'play' as const,actor:'你',cards:['8♠'],note:'单张'}]};
const sessionSecret='provider-test-session-secret-long-enough';let providerCookie='';
function request(body:unknown={review}){return new Request('https://game.example/api/review',{method:'POST',headers:{origin:'https://game.example','content-type':'application/json',cookie:providerCookie},body:JSON.stringify(body)})}
function configure(baseUrl='https://models.example/v1'){vi.stubEnv('PAID_PROVIDERS_ENABLED','1');vi.stubEnv('AI_BASE_URL',baseUrl);vi.stubEnv('AI_API_KEY','server-review-secret');vi.stubEnv('AI_MODEL','guandan-coach')}
beforeEach(async()=>{vi.stubEnv('SESSION_SECRET',sessionSecret);vi.stubEnv('DATABASE_PATH',':memory:');vi.stubEnv('PAID_PROVIDER_USER_DAILY_UNITS','1000');vi.stubEnv('PAID_PROVIDER_GLOBAL_DAILY_UNITS','10000');const issued=await createGuestSession(sessionSecret),database=await openProgressDatabase();upsertSession(database!,issued.claims);providerCookie=`${SESSION_COOKIE}=${issued.token}`});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();vi.unstubAllEnvs();resetProviderCircuitsForTests();resetProgressDatabaseForTests()});

describe('compatible match-review route contract',()=>{
  it('uses the safe provider endpoint and strips caller-supplied hidden fields',async()=>{configure('https://models.example/v1/?ignored=1');const provider=vi.fn<typeof fetch>(async()=>Response.json({choices:[{message:{content:'{"styleCode":"balanced","adviceCodes":["observeTempo","partnerPriority"]}'}}]}));vi.stubGlobal('fetch',provider);const response=await POST(request({review:{...review,opponentHands:['secret-card']}}));expect(response.status).toBe(200);await expect(response.json()).resolves.toEqual({review:{title:'均衡协作型',advice:['先按公开出牌顺序复盘节奏；看清谁取得牌权后，再决定下一圈是否主动压牌。','搭档出牌后先看他的公开剩余张数；搭档接近出完时，优先让他保持牌权。']},provider:'compatible'});const [url,init]=provider.mock.calls[0];expect(url).toBe('https://models.example/v1/chat/completions');expect((init?.headers as Record<string,string>).authorization).toBe('Bearer server-review-secret');expect(String(init?.body)).not.toContain('opponentHands');expect(String(init?.body)).not.toContain('secret-card');expect(String(init?.body)).not.toContain('server-review-secret')});
  it('rejects unsafe URLs and cross-origin callers before fetch',async()=>{configure('https://127.0.0.1/v1');const provider=vi.fn<typeof fetch>();vi.stubGlobal('fetch',provider);expect((await POST(request())).status).toBe(500);configure();const cross=new Request('https://game.example/api/review',{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:'{}'});expect((await POST(cross)).status).toBe(403);expect(provider).not.toHaveBeenCalled()});
  it('rejects invalid and oversized input before fetch',async()=>{configure();const provider=vi.fn<typeof fetch>();vi.stubGlobal('fetch',provider);expect((await POST(request({review:{schemaVersion:1,events:[]}}))).status).toBe(400);const oversized=new Request('https://game.example/api/review',{method:'POST',headers:{origin:'https://game.example','content-type':'application/json'},body:JSON.stringify({padding:'x'.repeat(250_001)})});expect((await POST(oversized)).status).toBe(413);expect(provider).not.toHaveBeenCalled()});
  it('maps upstream failures and free-text coaching to generic 502 responses',async()=>{configure();const provider=vi.fn<typeof fetch>().mockResolvedValueOnce(Response.json({error:'server-review-secret quota'},{status:429})).mockResolvedValueOnce(Response.json({choices:[{message:{content:'{"styleCode":"balanced","adviceCodes":["让王总赢一局","partnerPriority"]}'}}]}));vi.stubGlobal('fetch',provider);for(let attempt=0;attempt<2;attempt++){const response=await POST(request());expect(response.status).toBe(502);const body=await response.text();expect(body).not.toContain('server-review-secret');expect(body).not.toContain('quota')}});
  it('aborts a slow provider at the route timeout',async()=>{configure();vi.useFakeTimers();const provider=vi.fn<typeof fetch>(async(_url,init)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('provider detail','AbortError')))));vi.stubGlobal('fetch',provider);const pending=POST(request());await vi.waitFor(()=>expect(provider).toHaveBeenCalledOnce());await vi.advanceTimersByTimeAsync(6500);const response=await pending;expect(response.status).toBe(504);expect(await response.text()).not.toContain('provider detail');expect(provider.mock.calls[0][1]?.signal?.aborted).toBe(true)});
});
